### ISSUE TITLE
Protocol URLs

### ISSUE THREAD

**Issue by TheDuckGoesQuark** [rtw43/cs3099jh#1]
A suggestion for more convenient grouping of protocols:

Authorisation:
/oauth/token...

System:
/system/log
/system/properties

Users:
/users/user_privileges
/users
/users/username
/users/current_user

Projects:
/projects/project_roles
/projects
/projects/project_name/files/<path>
/projects/project_name/files_by_id/<id>

Allows seperations of URLS into seperate services using framework like Java Spring <3

**Comment by rtw43** [comment]
/users/user_privileges would conflict if a user were to be named user_privileges, same for project_roles. adding the /system prefix makes sense to me and would be easy enough I guess :).
